name: navigator
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlong: ^0.6.1
  flutter_map: any
  flutter_map_marker_cluster: any
  flutter_map_marker_popup: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/SVU.kml
    - lib/assets/images/

